// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBFBvRZmaYn1iwJSTjNzi5RlPNtQQFt0',
    appId: '1:856958118631:web:d7afa50ba86543169d9042',
    messagingSenderId: '856958118631',
    projectId: 'finalexamappdev',
    authDomain: 'finalexamappdev.firebaseapp.com',
    storageBucket: 'finalexamappdev.appspot.com',
    measurementId: 'G-C7T8E2VP2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPl2LpgDFGY_RQ93LVEzcYiqwdI3qCPq8',
    appId: '1:856958118631:android:a6ba75e0b1ab906d9d9042',
    messagingSenderId: '856958118631',
    projectId: 'finalexamappdev',
    storageBucket: 'finalexamappdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5d2h6txo0h8hvv9B8oY2mBWdMzqQUY4',
    appId: '1:856958118631:ios:c163984f0411597f9d9042',
    messagingSenderId: '856958118631',
    projectId: 'finalexamappdev',
    storageBucket: 'finalexamappdev.appspot.com',
    androidClientId: '856958118631-jpgsd02mpd4ikop36lfhnh3e7bk250fd.apps.googleusercontent.com',
    iosClientId: '856958118631-524nnm8ah321018gr29ckabh82nq90ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5d2h6txo0h8hvv9B8oY2mBWdMzqQUY4',
    appId: '1:856958118631:ios:c163984f0411597f9d9042',
    messagingSenderId: '856958118631',
    projectId: 'finalexamappdev',
    storageBucket: 'finalexamappdev.appspot.com',
    androidClientId: '856958118631-jpgsd02mpd4ikop36lfhnh3e7bk250fd.apps.googleusercontent.com',
    iosClientId: '856958118631-524nnm8ah321018gr29ckabh82nq90ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARBFBvRZmaYn1iwJSTjNzi5RlPNtQQFt0',
    appId: '1:856958118631:web:e29df5ab178038289d9042',
    messagingSenderId: '856958118631',
    projectId: 'finalexamappdev',
    authDomain: 'finalexamappdev.firebaseapp.com',
    storageBucket: 'finalexamappdev.appspot.com',
    measurementId: 'G-FN3L2YJH8Z',
  );

}